apiVersion: v1
kind: Pod
metadata:
  name: Config-Pod
spec: 
  containers:
  - name: config-pod 
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: configmap-demo-pod  # Name of the ConfigMap
          key: course  # Key in the ConfigMap
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: configmap-demo-pod  # Name of the ConfigMap
          key: trainer  # Key in the ConfigMap

