apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeport
  labels:
    app: nginx-node
    demo: service
spec: 
  containers:
  - name: nginx-pod 
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-nodeport
spec:
  type: nodePort
  selector:
    app: nginx-node
    demo: service
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80  #container port 